### PR TITLE
Fix #45 and #46 - Fix memory leak and segfault

### LINKED ISSUE #45: Memory leak
Hi!

Memory leaks began to appear after this commit https://github.com/albanm/node-libxslt/commit/fcce1298b8c84c3fc26727931a15fc75785840b7

Here are some examples of measurements:
```
(before) vs (after) in megabytes

counter = 1e2
43 vs 43

counter = 1e3
220 vs 420

counter = 3e3
240 vs 1261
```

Test code:
```javascript
'use strict';

var libxslt = require('libxslt');

var xml = '<?xml version="1.0" encoding="utf-8"?>\n<root>';
	for (let i = 0; i < 1e3; i++) {
		xml += `<item>${i}</item>`;
	}
	xml += '</root>';

var xsl = '<?xml version="1.0" encoding="utf-8"?>\n' +
	'<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">' +
	'<xsl:output version="1.0" indent="no" omit-xml-declaration="yes" />' +
	'<xsl:template match="/"><xsl:apply-templates select="root/item" /></xsl:template>' +
	'</xsl:stylesheet>'
;

var xslObj = libxslt.parse(xsl);


var rss = process.memoryUsage().rss;

var counter = 1e2;

for (let i = 0; i < counter; i++) {
	xslObj.apply(xml, function () {});
}

console.log(Math.round((process.memoryUsage().rss - rss) / Math.pow(2, 20)));
```

Unfortunately, segfault occurs without `SaveToPersistent` worker arguments (details here https://github.com/albanm/node-libxslt/issues/28).
But when arguments are saved, GC can't collect them, and memory usage is growing permanently with every call of transform.

### LINKED ISSUE #46: Segmentation fault occurs when transform returns empty result
Test code:

``` javascript
var libxslt = require('libxslt');

var xml = '<?xml version="1.0" encoding="utf-8"?>\n<root></root>';
var xsl = '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">' +
    '<xsl:template match="/"></xsl:template>' +
    '</xsl:stylesheet>'
;

var xslObj = libxslt.parse(xsl);

xslObj.apply(xml);
```

### PR DESCRIPTION
**Pull request by alejo90**
- Fixed #45 by removing call to `worker-SaveToPersistent`
- Fixed #46 by checking null pointer and assigning empty string if pointer was null

Thanks to @cem for the help

### CODE REVIEW

**Comment by tornillo** [comment]
Hi, @alejo90!
Thank you for trying to solve a problem with a memory leak!
However,  `SaveToPersistent` can't simply be removed, because https://github.com/albanm/node-libxslt/issues/45#issue-125604047 (bottom part of message about segfault).

**Comment by cem** [comment]
What I remember from our quick investigation with @alejo90 is that there was a bug with `SaveToPersistent` and the objects didn't get destroyed with the worker. As a workaround we should try keeping the necessary Local<> references in the worker's scope.

**Comment by alejo90** [comment]
Hi @tornillo, we were wary of removing the call to `SaveToPersistent`. We executed your test code with 20000 iterations several times and didn't encounter a segfault. Memory usage, on the other hand, came down from 8gb to 150mb. If you can provide a test case that produces the segfault, we would happily track it down.

**Comment by tornillo** [comment]
@alejo90, without `SaveToPersistent` memory usage is really reduced in test from https://github.com/albanm/node-libxslt/issues/45#issue-125604047

Test case, which cause segfault at every run of `node test.js`, can be found here https://github.com/albanm/node-libxslt/issues/28#issuecomment-154887587
(installation of 'segfault-handler' is not necessary)

My test environment at the moment: CentOS 3.10 x86_64, NodeJS 6.5

**Comment by gagern** [comment]
See #53 for my take on these. Do you have a test setup which would reliably distinguish uncollected garbage from actually leaked memory?

**Comment by gagern** [comment]
> As a workaround we should try keeping the necessary `Local<>` references in the worker's scope.

Which scope would that be? Afaik the Worker may not make use of any V8 API, since V8 is designed to be used synchroneously. So you can't have a scope, and you can't have local variables. That't the whole point behind that persistent storage: being able to keep things around for the lifetime of the worker.

> objects didn't get destroyed with the worker.

See https://github.com/albanm/node-libxslt/issues/45#issuecomment-246409826. If you were using the original test from that issue, your workers were probably still working, so it makes perfect sense that nothing wasn't destroyed yet. I see that the workers get destroyed pretty late, only when pretty much all of them have finished. Not surprising, although requesting parallel operations in 2k threads is probably a bad idea for real life tasks.

**Comment by alejo90** [comment]
> See #45 (comment). If you were using the original test from that issue, your workers were probably still working, so it makes perfect sense that nothing wasn't destroyed yet. I see that the workers get destroyed pretty late, only when pretty much all of them have finished. Not surprising, although requesting parallel operations in 2k threads is probably a bad idea for real life tasks.

@gagern we did notice that workers were still working. I forgot to mention that we changed the test case to use promises so that we waited for the work to finish. Even forcing gc via `global.gc()` after the work had finished and waiting additional time to give the gc opportunity to run didn't free any of the memory. We also verified that `ApplyWorker's` destructor is never called.

**Comment by gagern** [comment]
> We also verified that `ApplyWorker`'s destructor is never called.

I added a print to its destructor, and it got called.

I just changed the parallel application to a serial one, launching each `apply` after the previous finished. 1e3 runs reported 176G of memory, 1e4 reported 194G. So at that point the resource requirement apparently is no longer proportional to the number of runs. Not sure what to make of this.

**Comment by alejo90** [comment]
I don't know if it matters, but we tested on node 6.5.0, npm 3.10.7, windows 7 x64 and visual studio community 2015 update 3.

**Comment by gagern** [comment]
Node 6.5.0 via nvm on Gentoo Linux x86. Doubt it matters, though, since I can reproduce the observations. My main worry is the fact that the massive amounts of occupied memory neither go away after garbage collection, nor are reported by valgrind. I don't know how to interpret that.

**Comment by alejo90** [comment]
I noticed that `StylesheetAsync` doesn't call `SaveToPersistent` on `StylesheetWorker`. Why does `ApplyWorker` require it and `StylesheetWorker` doesn't?

**Comment by gagern** [comment]
`StylesheetAsync` only takes a single argument, namely the callback, and the `Nan::Callback` class takes care of storing that in a `Persistent` handle of its own. The document is libxml-copied in synchronous code and the stylesheet built from that copy. `ApplyAsync` on the other hand takes five arguments in addition to the callback, and most of those need to be available for the postprocessing step, so we need to keep them around.

**Comment by tornillo** [comment]
> I just changed the parallel application to a serial one, launching each apply after the previous finished. 1e3 runs reported 176G of memory, 1e4 reported 194G. So at that point the resource requirement apparently is no longer proportional to the number of runs. Not sure what to make of this.

In serial calls (or in synchronous mode of apply method) memory does not wasted.
In real applications only parallel calls do matter. Every "second" parallel call eats memory... And this behavior does not depend on size of input xml. So https://github.com/albanm/node-libxslt/pull/53 no helps.

**Comment by alejo90** [comment]
I gave this another pass. Since the segfault happens because the xml document is freed before the xslt document, I saved the document to persistent and nothing else. Final memory usage is, of course, higher than with my first attempt, but it's not as high as when everything is stored. The code I used to test is:

```
const libxslt = require('./index');

let xml = '<?xml version="1.0" encoding="utf-8"?>\n<root>';
for (let i = 0; i < 1e3; i++) {
  xml += `<item>${i}</item>`;
}
xml += '</root>';

const xsl = '<?xml version="1.0" encoding="utf-8"?>\n' +
  '<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">' +
  '<xsl:output version="1.0" indent="no" omit-xml-declaration="yes" />' +
  '<xsl:template match="/"><xsl:apply-templates select="root/item" /></xsl:template>' +
  '</xsl:stylesheet>'
;

const xslObj = libxslt.parse(xsl);

const rss = process.memoryUsage().rss;

const counter = 2e4;

const actions = [];

for (let i = 0; i < counter; i++) {
  const promise = new Promise((resolve, reject) => {
    xslObj.apply(xml, (err, result) => {
      if (err != null) {
        console.log('error', err);
        reject(err);
      } else {
        resolve(result);
      }
    });
  });
  actions.push(promise);
}

Promise.all(actions).then(() => {
	console.log(Math.round((process.memoryUsage().rss - rss) / Math.pow(2, 20)));
	console.log('force gc');
	global.gc();

	setTimeout(() => {
  	console.log(Math.round((process.memoryUsage().rss - rss) / Math.pow(2, 20)));
	}, 5000);
}).catch(err => console.log(err));
```

I also tested for the memory leak with:

```
require('segfault-handler').registerHandler('crash.log');

const libxslt = require('./index');

const xml = '<?xml version="1.0" encoding="utf-8"?>\n<root></root>';
const actions = [];
const transform = () => {
  const xslFile = new Promise((resolve, reject) => {
    libxslt.parseFile('./test.xsl', (err, xslObject) => {
      if (err != null) {
        reject(err);
      } else {
        resolve(xslObject);
      }
    });
  });
  const transformed = xslFile.then((xslObject) => {
    return new Promise((resolve, reject) => {
      xslObject.apply(xml, (err, result) => {
        if (err != null) {
          reject(err);
        } else {
          resolve(result);
        }
      });
    });
  });
  actions.push(transformed);
}

let counter = 1000;

while (counter--) {
  transform();
}

Promise.all(actions).then(() => console.log('finished'));
```

**Comment by gagern** [comment]
I would assume that one can construct a situation where not saving the stylesheet will cause problems. Try examples where the XSL is constructed on the fly, and JavaScript code holds no reference to it after the application got triggered. Storing less information feels like working around the problem without really understanding it. Not that I claim to actually understand why the memory doesn't get freed as it should…

**Pull request closed without merging**
