### PR TITLE
Compatibility PR for node 12

### PR DESCRIPTION
**Pull request by renanccastro**
Please, disregard the changes to the package.json name, if you want it merged I can change it back :)

This PR makes this lib compatible with node 12.

There is also work from @alexdee2007 fork, so also thanks!

Thanks for the good work!!

### CODE REVIEW

**Comment by albanm** [comment]
Could you check why the travis build fails ? I don't know it the appveyor was still green before, but maybe it should be checked also.

Does this PR break any compatibility ? Should it be released in a major or a patch version ?

Nice to see that some people still put some work in this module ! I know I haven't done it myself for a long time. Instead of a PR, would you be interested in a ownership transfer of the npm module ?

**Comment by renanccastro** [comment]
Sorry for the late response @albanm crazy days. I will check the CI, but it's because the node hasn't been updated on it to v12.
About the future of the project, if you want to transfer the ownership I would gladly accept, but I think the project is stable as it is and we can help it with PR's. It's your call :) 

I will update the PR for making the CI green today or tomorrow. Thanks again.

**Comment by renanccastro** [comment]
Checks are passing!

**Comment by albanm** [comment]
Merged and released. Thanks !

**Comment by MartijnR** [comment]
Whooohooo! :party: Super happy with this. Thanks @renanccastro & @albanm!

**Pull request merged**
