### PR TITLE
new function .applyToString to respect omit-xml-declaration

### PR DESCRIPTION
**Pull request by neu-rah**
Stylesheet.prototype.applyToString=function(source, params,callback)

@param {string|Document} source - The XML content to apply the stylesheet to given as a string or a [libxmljs document]
@param {object} [params] - Parameters passed to the stylesheet 
@param {Stylesheet~applyCallback} [callback] - Omit for sync mode or The callback that handles the response. Expects err and a string
@return {string} - with the resulting transformation on sync mode

### CODE REVIEW

**Comment by neu-rah** [comment]
have no idea of what that continuous-integration/appveyor/pr fail is :\

**Comment by neu-rah** [comment]
was it something I've done wrong? it is compiling on my system

**Comment by gagern** [comment]
I've no clue either as to why Appveyor is failing. Doesn't look related to your changes. It's failing on my pull requests as well. In https://github.com/albanm/node-libxslt/pull/14#issuecomment-114375931 @albanm indicated that this is a known problem.

Since I'm just a contributor, not a maintainer here, I don't think I should be the one to merge your request. But the final diff looks mostly good to me, even though some of the intermediate stages were a bit scary mixtures. I can imagine @albanm might be willing to merge this as is.

If I were to indicate areas for possible improvement, I'd suggest
* squash everything to a single commit off master. Probably best achieved using `git fetch origin && git reset --soft origin/master && git commit -c 2ad02cf1` followed by `git push -f`. That would lead to a cleaner history.
* Drop `.npmignore`, merge its content into `.gitignore`. Or leave it out of this commit, and open a separate request so it can be discussed. Not really related to the issue at hand.
* Check the output of the unit test more thoroughly, particularly with respect to the different escaping settings.
* Add some unit test for xhtml output.

**Comment by neu-rah** [comment]
agree 100%, thanks for precious help, I was really looking for a way of cleaning up the intermediate mess  and suspicious of not having pulled the correct one.

**Comment by neu-rah** [comment]
all that would invalidate the pull request?

**Comment by gagern** [comment]
No. A push, even a forced push, will simply update this pull request. As long as the branch name (“master” in your case) remains the same.

**Comment by albanm** [comment]
Don't worry about appveyor, I never actually made it work.

I will try to have a better look and merge this today. I also have to update the README accordingly.

**Comment by albanm** [comment]
Ok, so I was not so happy about extending the API with new functions. See https://github.com/albanm/node-libxslt/commit/ab53af33026d9945700790f2280331a819c98173

I just made using xsltSaveResultToString the normal behavior of "apply" when returning a string (whitch it does if it was given a String as input). No extension to the API, less code redundancy and I don't think there is a high risk of regression.

Thanks for the PR, the core of the fix comes from it. Tell me if this suits you and I will release it soon.

**Comment by neu-rah** [comment]
having to submit a string to get a string output invalidates my parsed document store, documents have to be serialized and parsed on every application.

**Comment by albanm** [comment]
Ok, I will do something about this. It is now possible with only JS
modifications.

2015-11-16 7:01 GMT+01:00 Rui Azevedo <notifications@github.com>:

**Comment by albanm** [comment]
How about this ?

https://github.com/albanm/node-libxslt/commit/abab0810cab959394e54a181518cac7cb1ac3df9

I regret not having created from the start a more extensible API with a simple 'options' parameter. But I don't want to multiply the functions. So this is the compromise for now.

**Comment by albanm** [comment]
Well I am not sure I understand perfectly, but to maintain compatibility a second and last parameters should be "params" ie an object passed to the xslt. See what I did here, I believe it's alright: https://github.com/albanm/node-libxslt/blob/master/index.js#L100

**Comment by gagern** [comment]
I forgot about the `params` argument, so the indices I mentioned were off by one.

> See what I did here …

That's the general idea, yes. I think this might lead to confusion if people mix up the argument order. If you do `s.apply(source, params, callback, options)` by accident, then `options` will be discarded but not cause an exception. I wonder whether one should check that `callback === undefined` before shifting the callback into position. On the other hand, this kind of confusion is no worse than passing extra arguments to any JavaScript function, so perhaps this is just fine.

I'm more worried about the `outputString === undefined` part. This means that setting `outputString` to `false` or `null` has a different effect than leaving it out. A simple `!outputString` would seem more appropriate to me.

The name `outputString` is somewhat confusing to me as well, since I associate arguments starting in `output` as references which will *receive* the output of the function. Similar to the result documents in the internal calls to native code. `outputAsString` would be better in my opinion. Or `outputFormat = "string"`, because in that case you can also do `outputFormat = "buffer"` and `outputFormat = "stream"` one day if you choose to.

By the way, you might want to replace the `libxmljs.parseXml` call by its asynchroneous version one day, I think. At least if you received a `callback` argument yourself. It's `libxml.Document.fromXmlAsync(buffer, callback)`.

Oh, which reminds me: don't you want to accept buffers on input as well? The `typeof source === 'string'` doesn't capture that. I'm not sure whether we can delegate the handling of character encoding to libxml, or whether we'd have to do that ourselfs. But since for most applications it should be sufficient to support UTF-8 and error out on anything else, that should be possible reasonably well.

**Comment by albanm** [comment]
I agree with your remark about outputString. I just switched to a outputFormat option.

Other remarks are interesting as well, but are about less pressing matters. They can be worked on later without API modifications.

**Comment by gagern** [comment]
Do you want me to file an issue for any of them, lest we forget about them?

**Comment by albanm** [comment]
Yes, definitely.

**Pull request merged**
