### PR TITLE
Add support for Apple silicon

### PR DESCRIPTION
**Pull request by jie17**
- Test is passing
- It's working in my project using node-libxslt

### CODE REVIEW

**Review by javorosas — APPROVED** [review]

**Review by javorosas — COMMENTED** [review]
Sorry for the earlier approval, I didn't know I would be able to do it, and not sure how to un-approve

**Comment by lognaturel** [comment]
It’s no problem @javorosas. Did you actually give it a try? It looks good to me but I was waiting to get my new machine and try it myself before approving. I can’t do releases, though.

**Comment by javorosas** [comment]
> It’s no problem @javorosas. Did you actually give it a try? It looks good to me but I was waiting to get my new machine and try it myself before approving. I can’t do releases, though.

I did. I installed it like this locally on an M1 Pro and it worked fine.

```
$ npm i git://github.com/jie17/node-libxslt.git#apple-silicon
```

What I couldn't do though was installing it inside a Docker container with linux/arm64 architecture. I'm getting the following output:

```
#27 66.92 > libxslt@git://github.com/jie17/node-libxslt.git#45469a9dbdf9f787e872ef5efeb665894c4d5c1f install /server/node_modules/libxslt
#27 66.92 > node-gyp rebuild
#27 66.92
#27 67.19 make: Entering directory '/server/node_modules/libxslt/build'
#27 67.19   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/common.o
#27 67.20 In file included from ../deps/libxslt/libexslt/common.c:2:0:
#27 67.20 ../deps/libxslt/libexslt/libexslt.h:15:20: fatal error: config.h: No such file or directory
#27 67.20  #include "config.h"
#27 67.20                     ^
#27 67.20 compilation terminated.
#27 67.20 deps/libexslt.target.mk:131: recipe for target 'Release/obj.target/libexslt/deps/libxslt/libexslt/common.o' failed
#27 67.20 make: Leaving directory '/server/node_modules/libxslt/build'
#27 67.20 make: *** [Release/obj.target/libexslt/deps/libxslt/libexslt/common.o] Error 1
#27 67.20 gyp ERR! build error
#27 67.20 gyp ERR! stack Error: `make` failed with exit code: 2
#27 67.20 gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
#27 67.20 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#27 67.20 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
#27 67.20 gyp ERR! System Linux 5.10.47-linuxkit
#27 67.20 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#27 67.20 gyp ERR! cwd /server/node_modules/libxslt
#27 67.20 gyp ERR! node -v v14.18.1
#27 67.20 gyp ERR! node-gyp -v v5.1.0
#27 67.20 gyp ERR! not ok
#27 67.91 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
#27 67.91 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#27 67.93 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#27 67.93 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#27 67.93
#27 67.97 npm ERR! code ELIFECYCLE
#27 67.97 npm ERR! errno 1
#27 67.98 npm ERR! libxslt@git://github.com/jie17/node-libxslt.git#45469a9dbdf9f787e872ef5efeb665894c4d5c1f install: `node-gyp rebuild`
#27 67.98 npm ERR! Exit status 1
#27 67.98 npm ERR!
#27 67.98 npm ERR! Failed at the libxslt@git://github.com/jie17/node-libxslt.git#45469a9dbdf9f787e872ef5efeb665894c4d5c1f install script.
#27 67.98 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#27 68.04
#27 68.04 npm ERR! A complete log of this run can be found in:
#27 68.04 npm ERR!     /root/.npm/_logs/2021-11-13T13_47_27_592Z-debug.log
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm install --quiet && npm cache clean -f]: exit code: 1
```

**Comment by samuelxing-okta** [comment]
> > It’s no problem @javorosas. Did you actually give it a try? It looks good to me but I was waiting to get my new machine and try it myself before approving. I can’t do releases, though.
> 
> @lognaturel I did. I installed it like this locally on an M1 Pro and it worked fine.
> 
> ```
> $ npm i git://github.com/jie17/node-libxslt.git#apple-silicon
> ```
> 
> What I couldn't do though was installing it inside a Docker container with linux/arm64 architecture. I'm getting the following output:
> 
> ```
> #27 66.92 > libxslt@git://github.com/jie17/node-libxslt.git#45469a9dbdf9f787e872ef5efeb665894c4d5c1f install /server/node_modules/libxslt
> #27 66.92 > node-gyp rebuild
> #27 66.92
> #27 67.19 make: Entering directory '/server/node_modules/libxslt/build'
> #27 67.19   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/common.o
> #27 67.20 In file included from ../deps/libxslt/libexslt/common.c:2:0:
> #27 67.20 ../deps/libxslt/libexslt/libexslt.h:15:20: fatal error: config.h: No such file or directory
> #27 67.20  #include "config.h"
> #27 67.20                     ^
> #27 67.20 compilation terminated.
> #27 67.20 deps/libexslt.target.mk:131: recipe for target 'Release/obj.target/libexslt/deps/libxslt/libexslt/common.o' failed
> #27 67.20 make: Leaving directory '/server/node_modules/libxslt/build'
> #27 67.20 make: *** [Release/obj.target/libexslt/deps/libxslt/libexslt/common.o] Error 1
> #27 67.20 gyp ERR! build error
> #27 67.20 gyp ERR! stack Error: `make` failed with exit code: 2
> #27 67.20 gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> #27 67.20 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
> #27 67.20 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
> #27 67.20 gyp ERR! System Linux 5.10.47-linuxkit
> #27 67.20 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> #27 67.20 gyp ERR! cwd /server/node_modules/libxslt
> #27 67.20 gyp ERR! node -v v14.18.1
> #27 67.20 gyp ERR! node-gyp -v v5.1.0
> #27 67.20 gyp ERR! not ok
> #27 67.91 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> #27 67.91 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
> #27 67.93 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> #27 67.93 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
> #27 67.93
> #27 67.97 npm ERR! code ELIFECYCLE
> #27 67.97 npm ERR! errno 1
> #27 67.98 npm ERR! libxslt@git://github.com/jie17/node-libxslt.git#45469a9dbdf9f787e872ef5efeb665894c4d5c1f install: `node-gyp rebuild`
> #27 67.98 npm ERR! Exit status 1
> #27 67.98 npm ERR!
> #27 67.98 npm ERR! Failed at the libxslt@git://github.com/jie17/node-libxslt.git#45469a9dbdf9f787e872ef5efeb665894c4d5c1f install script.
> #27 67.98 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> #27 68.04
> #27 68.04 npm ERR! A complete log of this run can be found in:
> #27 68.04 npm ERR!     /root/.npm/_logs/2021-11-13T13_47_27_592Z-debug.log
> ------
> failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm install --quiet && npm cache clean -f]: exit code: 1
> ```

I got the same error while trying to install the lib inside the Docker with linux/arm64 architecture. This error is quite confusing.... isn't the `config.h` file existed already? under this folder, https://github.com/albanm/node-libxslt/tree/master/deps/libxslt.config/linux/arm. There must be somewhere the config is still not correct..any ideas?

**Comment by chyyran** [comment]
Try `arm64`

**Comment by sharq88** [comment]
When installed directly on M1 it uses `mac/arm64` when installed through docker it uses `linux/arm64`. 
With that directory it goes quite far - added here: 
https://github.com/sharq88/node-libxslt

However it now fails somewhere at the end: 
```
CXX(target) Release/obj.target/node-libxslt/src/stylesheet.o
#16 31.84   SOLINK_MODULE(target) Release/obj.target/node-libxslt.node
#16 31.85 /opt/app-root/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node: file not recognized: file format not recognized
#16 31.85 collect2: error: ld returned 1 exit status
```
@lognaturel any idea what the reason of the above error might be?

**Comment by buzzb0x** [comment]
Is someone interested in merging this?

**Review by lognaturel — APPROVED** [review]
Verified working.

**Pull request merged**
